### ISSUE TITLE
Error when trying to run cucumber tests

### ISSUE THREAD

**Issue by turbogeek421** [bearded/ruby-ldap#33]
I'm currently trying to update a (very) old rails application but am running into this error when trying to run cucumber tests:

```
ruby1.8: symbol lookup error: /vagrant/vendor/gems/ruby/1.8/gems/ruby-ldap-0.9.17/lib/ldap.so: undefined symbol: rb_hash_dup
```

Rails 2.3.18
Ruby 1.8.7

Any ideas?

**Comment by dacamp** [comment]
[rb_hash_dup](http://rxr.whitequark.org/mri/ident?v=1.8.7-p374;i=rb_hash_dup) was added to Ruby 1.9.  Commit 01c0fdf added it to the repo, which appears to only be in version 0.9.17.  Try to pin your version to 0.9.16 and let me know if that works.

Documentation should probably be updated to include as much.

**Comment by turbogeek421** [comment]
Update my Gemfile to specify '0.9.16' and that seems to have fixed the issue.

Thanks @dacamp
