### ISSUE TITLE
Parsing error with CRLF

### ISSUE THREAD

**Issue by doppelreim** [bearded/ruby-ldap#38]
Parsing a file with windows line endings (CRLF) fails with the error `Improperly continued line:`.

According to https://tools.ietf.org/html/rfc2849:
> SEP                      = (CR LF / LF)

I assume this is because the regex at https://github.com/bearded/ruby-ldap/blob/0.9.17/lib/ldap/ldif.rb#L195 does not match `\r\n`.

Maybe changing it to `/\A\s*\z/` would help?

**Comment by bearded** [comment]
Please try a version `0.9.19`.

**Comment by doppelreim** [comment]
Yeah!
Thanks a lot :)
