### ISSUE TITLE
issue with ruby-ldap version 0.9.10 and 0.9.11 on ubuntu 10.04 64bit

### ISSUE THREAD

**Issue by ghost** [bearded/ruby-ldap#7]
i have installed libldap2-dev and libssl-dev
when i tried sudo gem install ruby-ldap then get below error

saslconn.c:19:23: error: sasl/sasl.h: No such file or directory
saslconn.c: In function ‘rb_ldap_sasl_interaction’:
saslconn.c:34: error: ‘sasl_interact_t’ undeclared (first use in this function)
saslconn.c:34: error: (Each undeclared identifier is reported only once
saslconn.c:34: error: for each function it appears in.)
saslconn.c:34: error: ‘interact’ undeclared (first use in this function)
saslconn.c:48: error: ‘SASL_CB_LIST_END’ undeclared (first use in this function)
saslconn.c:53: error: ‘SASL_CB_GETREALM’ undeclared (first use in this function)
saslconn.c:59: error: ‘SASL_CB_AUTHNAME’ undeclared (first use in this function)
saslconn.c:65: error: ‘SASL_CB_USER’ undeclared (first use in this function)
make: **\* [saslconn.o] Error 1

also when i type ldapsearch -x -H ldaps://ldap.01.com:636 then it gives me result as below
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

when i installed libgsasl7-dev
and then gem install ruby-ldap -v=0.9.9 
it works fine

**Comment by alokswain** [comment]
Documentation relevant with Ruby 2.2.3 and Ubuntu 18.04. Thanks.

**Comment by vmvwebworks** [comment]
for me worked with `sudo apt install libldap2-dev` in Ubuntu :)
